<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="1">

  <testsuite name="url"
    errors="0" failures="1" hostname="" id="" package="createCompanySarma" skipped="0"
    tests="1" time="35.73" timestamp="Sun, 14 Feb 2016 15:16:50 GMT">
  
    <testcase name="check url valid information" time="35.73" assertions="12">

    

    

    

    

    

    

    

      <failure message="check for invalid url">    at Object.module.exports.check url valid information (D:\work\nightwatch\nightwatch-0.8.16\tests\createCompanySarma\url.js:50:25)
    at Module.call (D:\work\nightwatch\nightwatch-0.8.16\lib\runner\module.js:63:34)
    at D:\work\nightwatch\nightwatch-0.8.16\lib\runner\testcase.js:97:29
    at _fulfilled (D:\work\nightwatch\nightwatch-0.8.16\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (D:\work\nightwatch\nightwatch-0.8.16\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (D:\work\nightwatch\nightwatch-0.8.16\node_modules\q\q.js:796:13)
    at D:\work\nightwatch\nightwatch-0.8.16\node_modules\q\q.js:556:49
    at runSingle (D:\work\nightwatch\nightwatch-0.8.16\node_modules\q\q.js:137:13)
    at flush (D:\work\nightwatch\nightwatch-0.8.16\node_modules\q\q.js:125:13)
    at process._tickCallback (node.js:355:11)</failure>

    

    

    

    
    </testcase>
  
  
  </testsuite>
</testsuites>
